plugins {
    id 'java'
}

allprojects {
    group = 'com.infiniteconquest'
    version = '0.1.0-alpha'
    repositories { mavenCentral() }
}

subprojects {
    apply plugin: 'java'
    java {
        toolchain { languageVersion = JavaLanguageVersion.of(17) }
    }
    tasks.withType(Test).configureEach { useJUnitPlatform() }
}
