package com.infiniteconquest.core;

public enum CapitalPassive {
    OLYMPIAN_MUSTER,
    STORM_TITHE,
    CLOUDWARD,
    TIDAL_RENEWAL,
    TRIDENT_RESTORATION,
    DEEP_RESERVES,
    DEATHLESS_LEVY,
    FERRY_TOLL,
    TARTARUS_ENDURANCE,
    BLOODLUST,
    WAR_CAMP_DRILL,
    RELENTLESS_ADVANCE,
    AEGIS_FORMATION,
    ARCHIVED_FORESIGHT,
    OWLWARD,
    FORGE_EFFICIENCY,
    SALVAGE_FIRES,
    BRONZE_REGENERATION
}
